#!/bin/csh

#SBATCH --account mscms                         # charged account
#SBATCH --time 120                              # 30 minute time limit
#SBATCH --nodes 1                               # 2 nodes
#SBATCH --ntasks-per-node 16                    # 16 processes on each per node
#SBATCH --job-name enviroms                     # job name in queue (``squeue``)
#SBATCH --error enviroms-%j.err             # stderr file with job_name-job_id.err
#SBATCH --output enviroms-%j.out                 # stdout file
#SBATCH --mail-user=corilo@pnnl.gov  # email user
#SBATCH --mail-type END                        # when job ends
#SBATCH --reservation eber373-benchmarking


module purge                                   
module load intel/16.1.150
module load impi/5.1.2.150


export SLURM_CPU_BIND=none
mpirun -n 48 ~/enviroms/venv/bin/enviroMS run-di-workflow -r 48 --mpi /dtemp/mscms/enviroms/data/EnviromsFile.json
 
